Repository cherow/cherow, pull requests merged in 2018-12, with the labels that each got.

#239 build(cherow): add fuzz scripts to find bugs
  .gitignore
  packages/cherow/package.json
  packages/cherow/test/fuzz/cherow.js
  packages/cherow/test/fuzz/parser.js
  yarn.lock
Labels: build, workflow

#244 build(cherow): switch to eslump@2.0.0
  packages/cherow/package.json
  yarn.lock
Labels: build, chore

#256 fixes #254
  packages/cherow/src/parser/module.ts
  packages/cherow/src/parser/pattern.ts
  packages/cherow/src/parser/statements.ts
  packages/cherow/test/parser/module/export.ts
Labels: 1.6.x, bug

#266 chore: add prettier & pre-commit (fixes #178)
  .editorconfig
  .prettierignore
  package-lock.json
  package.json
  prettier.config.js
  scripts/list-changed-files.js
  scripts/prettier.js
Labels: workflow
