Repository cherow/cherow, pull requests merged in 2018-07, with the labels that each got.

#165 docs(*): add contributing.md
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#198 refactor(cherow); fix issues with nextToken
  packages/cherow/src/lexer/scan.ts
Labels: refactor

#202 refactor(cherow): simplify lexer code
  packages/cherow/src/chars.ts
  packages/cherow/src/lexer/numbers.ts
  packages/cherow/src/lexer/scan.ts
  packages/cherow/src/state.ts
  packages/cherow/src/types.ts
  packages/cherow/test/lexer/bigint.ts
  packages/cherow/test/lexer/lookahead.ts
  packages/cherow/test/lexer/onToken.ts
Labels: do not merge

#195 refactor(cherow): use table for perf.
  packages/cherow/src/chars.ts
  packages/cherow/src/lexer/common.ts
  packages/cherow/src/lexer/identifier.ts
Labels: refactor

#214 refactor(cherow): fixes a few edge cases
  packages/cherow/src/lexer/identifier.ts
  packages/cherow/src/lexer/scan.ts
  packages/cherow/src/parser/expressions.ts
  packages/cherow/src/parser/statements.ts
  packages/cherow/test/lexer/onToken.ts
Labels: do not merge

#218 refactor(cherow): WIP: fixes statement parsing
  packages/cherow/src/errors.ts
  packages/cherow/src/parser/statements.ts
  packages/cherow/test/parser/declarations/var.ts
  packages/cherow/test/parser/miscellaneous/terrible_bug.ts
  packages/cherow/test/parser/statements/debugger.ts
  packages/cherow/test/parser/statements/do.ts
  packages/cherow/test/parser/statements/empty.ts
  packages/cherow/test/parser/statements/expression.ts
  packages/cherow/test/parser/statements/for-await-of.ts
  packages/cherow/test/parser/statements/for-of.ts
  packages/cherow/test/parser/statements/for.ts
  packages/cherow/test/parser/statements/if.ts
  packages/cherow/test/parser/statements/return.ts
  packages/cherow/test/parser/statements/switch.ts
  packages/cherow/test/parser/statements/throw.ts
  packages/cherow/test/parser/statements/while.ts
  packages/cherow/test/parser/statements/with.ts
Labels: do not merge

#234 chore: git ignore dist and some files
  .gitignore
Labels: chore
