Repository cherow/cherow, pull requests merged in 2018-06, with the labels that each got.

#125 docs: fix typo & add badge
  README.md
Labels: documentation

#131 workflow: clean up (fix #130)
  lerna.json
  package-scripts.js
  package.json
  packages/cherow-cli/bin/cherow
  packages/cherow-cli/package.json
  packages/cherow-flow/package.json
  packages/cherow-minify/package.json
  packages/cherow-ts/package.json
  packages/cherow/.travis.yml
  packages/cherow/package.json
  yarn.lock
Labels: workflow

#144 refactor(cherow): clean up lexer/numeric.ts
  packages/cherow/src/lexer/numeric.ts
Labels: chore

#161 breaking(cherow): remove numeric separator (fixes #159)
  packages/cherow/README.md
  packages/cherow/src/lexer/common.ts
  packages/cherow/src/lexer/numeric.ts
  packages/cherow/test/lexer/numbers.ts
Labels: breaking

#169 chore: update yarn.lock
  yarn.lock
Labels: chore
